# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mfdbname', models.CharField(max_length=200)),
                ('bfdbname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsdb.Location'),
        ),
    ]
