# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='password',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='user',
        ),
    ]
