# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsdb', '0002_auto_20170728_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='base',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
